kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: devex-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 9090
    protocol: TCP
  - containerPort: 443
    hostPort: 9443
    protocol: TCP
