version: "3.8"
services:
  book-service:
    container_name: book-service
    image: book-service
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      BPL_DEBUG_ENABLED: "true"
      BPL_DEBUG_PORT: 9090
      BP_LIVE_RELOAD_ENABLED: "true"
