---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: book-service
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: book-service
spec:
  serviceAccountName: default
  source:
    git:
      url: https://github.com/ThomasVitale/developer-experience-java-kubernetes
      ref:
        branch: main
    subPath: 09-cartographer/basic/book-service
  build:
    env: 
      - name: BP_JVM_VERSION 
        value: "17.*"
  resources:
    limits:
      cpu: "2"
      memory: 756Mi
    requests:
      cpu: "0.1"
      memory: 756Mi
