---
apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: book-service
  labels:
    apps.kadras.io/workload-type: web
    apps.kadras.io/has-tests: "true"
    apps.kadras.io/language: java
    app.kubernetes.io/part-of: book-service
spec:
  source:
    git:
      url: https://github.com/ThomasVitale/developer-experience-java-kubernetes
      ref:
        branch: main
    subPath: 09-cartographer/basic/book-service
