# Build
custom_build(
    # Name of the container image
    ref = 'book-service',
    # Command to build the container image
    # On Windows, replace $EXPECTED_REF with %EXPECTED_REF%
    command = './gradlew bootBuildImage --imageName $EXPECTED_REF',
    # Files to watch that trigger a new build
    deps = ['build.gradle', './bin/main'],
    # Enables live reload
    live_update = [
        sync('./bin/main', '/workspace/BOOT-INF/classes')
    ]
)

# Deploy
k8s_yaml(['config/deployment.yml', 'config/service.yml'])

# Manage
k8s_resource('book-service', port_forwards=['8080:8080', '9090:9090'])
