version = 1

[install]
httpie.pkg-path = "httpie"
temurin-bin-24.pkg-path = "temurin-bin-24"
arconia-cli-flake.flake = "github:thomasvitale/arconia-cli-flake"
vscode-java-flake.flake = "github:thomasvitale/vscode-java-flake"

[vars]
FLOX_DISABLE_METRICS="true"

[profile]
common = '''
  export JAVA_HOME=$FLOX_ENV
'''

[options]
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
