apiVersion: apps/v1
kind: Deployment
metadata:
  name: music-service
  labels:
    app: music-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: music-service
  template:
    metadata:
      labels:
        app: music-service
    spec:
      containers:
        - name: music-service
          image: music-service
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 1001
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 8181
          env:
            - name: BPL_DEBUG_ENABLED
              value: "true"
            - name: BPL_DEBUG_PORT
              value: "9191"
          resources:
            requests:
              cpu: "0.2"
              memory: "1Gi"
            limits:
              memory: "1Gi"
