version = 1

[install]
httpie.pkg-path = "httpie"
graalvm-ce.pkg-path = "graalvm-ce"
graalvm-ce.version = "24.0.1"
arconia-cli-flake.flake = "github:thomasvitale/arconia-cli-flake"
pack.pkg-path = "pack"

[vars]
FLOX_DISABLE_METRICS="true"

[hook]
# on-activate = '''
#   # -> Set variables, create files and directories
#   # -> Perform initialization steps, e.g. create a python venv
#   # -> Useful environment variables:
#   #      - FLOX_ENV_PROJECT=/home/user/example
#   #      - FLOX_ENV=/home/user/example/.flox/run
#   #      - FLOX_ENV_CACHE=/home/user/example/.flox/cache
# '''

[profile]
# common = '''
#   gum style \
#   --foreground 212 --border-foreground 212 --border double \
#   --align center --width 50 --margin "1 2" --padding "2 4" \
#     $INTRO_MESSAGE
# '''
## Shell specific profiles go here:
# bash = ...
# zsh  = ...
# fish = ...

[services]
# myservice.command = "python3 -m http.server"

[include]
# environments = [
#     { dir = "../common" }
# ]

[options]
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
