version = 1

[install]
httpie.pkg-path = "httpie"
graalvm-ce.pkg-path = "graalvm-ce"
graalvm-ce.version = "24.0.1"

[vars]
FLOX_DISABLE_METRICS="true"

[hook]
# on-activate = """
#   export JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))
#   export PATH=$JAVA_HOME/bin:$PATH
# """

[profile]
# common = '''
#   gum style \
#   --foreground 212 --border-foreground 212 --border double \
#   --align center --width 50 --margin "1 2" --padding "2 4" \
#     $INTRO_MESSAGE
# '''
## Shell specific profiles go here:
# bash = ...
# zsh  = ...
# fish = ...

[services]
# myservice.command = "python3 -m http.server"

[include]
# environments = [
#     { dir = "../common" }
# ]

[options]
systems = [
  "aarch64-darwin",
  "aarch64-linux",
  "x86_64-darwin",
  "x86_64-linux",
]
