apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: book-service
build:
  artifacts:
    - image: book-service
      buildpacks:
        builder: docker.io/paketobuildpacks/builder-jammy-buildpackless-tiny
        buildpacks:
          - gcr.io/paketo-buildpacks/java
        env:
          - BP_JVM_VERSION=22
          - BP_LIVE_RELOAD_ENABLED=true
        dependencies:
          paths:
            - build.gradle
            - src/main/resources
            - bin/main
      sync:
        manual:
          - src: "src/main/resources/**/*"
            dest: /workspace/BOOT-INF/classes
            strip: src/main/resources/
          - src: "bin/main/**/*"
            dest: /workspace/BOOT-INF/classes
            strip: bin/main/

manifests:
  rawYaml:
  - config/deployment.yml
  - config/service.yml
