apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: demo
build:
  artifacts:
    - image: demo
      custom:
        buildCommand: ./gradlew bootBuildImage --imageName=$IMAGE --runImage docker.io/paketobuildpacks/ubuntu-noble-run-base
        dependencies:
          paths:
            - build.gradle
            - src/main/resources
            - build/classes/java/main
            #- bin/main
      sync:
        manual:
          - src: "src/main/resources/**/*"
            dest: /workspace/BOOT-INF/classes
            strip: src/main/resources/
          # - src: "bin/main/**/*"
          #   dest: /workspace/BOOT-INF/classes
          #   strip: bin/main/
          - src: "build/classes/java/main/**/*"
            dest: /workspace/BOOT-INF/classes
            strip: build/classes/java/main/

manifests:
  rawYaml:
  - config/deployment.yml
  - config/service.yml
